# Generated by Django 3.2.4 on 2021-08-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=9)),
                ('sell_value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('buy_value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('in_stock', models.PositiveIntegerField()),
                ('min_qte', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address_pattern', models.CharField(max_length=200)),
            ],
        ),
    ]
