# Generated by Django 3.2.4 on 2021-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='address_pattern',
            field=models.CharField(help_text='Designante regex of currencie address', max_length=200, verbose_name='address pattern'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='buy_value',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='buy value'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='code',
            field=models.CharField(error_messages={'unique': 'this code  already exists'}, help_text='Designant code of currencie', max_length=9, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='in_stock',
            field=models.PositiveIntegerField(verbose_name='max quantity'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='min_qte',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='min quantity'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='name',
            field=models.CharField(error_messages={'unique': 'this name already exists'}, help_text='Designant the name of currencie', max_length=20, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='sell_value',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='sell value'),
        ),
    ]
