# Generated by Django 3.2.4 on 2021-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0002_auto_20210815_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='favarite'),
        ),
    ]
