# Generated by Django 3.2.4 on 2021-08-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0003_currencies_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='buy_value',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='buy value'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='min_qte',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='min quantity'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='sell_value',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='sell value'),
        ),
    ]
