# Generated by Django 3.2.4 on 2021-08-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0004_auto_20210818_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='min_qte',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='min quantity'),
        ),
    ]
