# Generated by Django 3.2.4 on 2021-08-15 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('done', 'done'), ('pending', 'pending'), ('failed', 'failed')], max_length=9)),
                ('to_wallet_address', models.CharField(max_length=100)),
                ('send_amount', models.DecimalField(decimal_places=4, max_digits=6)),
                ('recieve_amount', models.DecimalField(decimal_places=4, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('currencie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencie', to='Currencies.currencies')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devise', to='Currencies.currencies')),
            ],
        ),
    ]
