# Generated by Django 3.2.4 on 2021-08-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_auto_20210816_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='reference'),
        ),
    ]
