# Generated by Django 3.2.4 on 2021-08-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Currencies', '0005_alter_currencies_min_qte'),
        ('Transactions', '0005_exchange_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=225, verbose_name='reciever wallet address')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='send amount')),
                ('recieve_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='recieve amount')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Currencies.currencies')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
