# Generated by Django 3.2.4 on 2021-08-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nom utilisateur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numero de telephone ')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom ')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=' Prénom ')),
                ('sponsor_id', models.PositiveIntegerField(blank=1, default=None, null=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('can_receive_notification', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('generate_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tried', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
