# Generated by Django 3.2.4 on 2021-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='togo', max_length=20),
        ),
    ]
