# Generated by Django 3.2.4 on 2021-08-15 18:18

import Authentication.validators
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Togo', help_text='Designant whether the client city is', max_length=20, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default=None, help_text='Designed the phone number of the client or user', max_length=20, null=True, validators=[Authentication.validators.PhoneNumberValidator()], verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with tihat username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nom Utilisateur'),
        ),
    ]
